version : '2.2'

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-alpine
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../src/main/docker/nginx.conf:/etc/nginx/nginx.conf:rw
      - ../src/main/docker/mime.types:/etc/nginx/mime.types:rw
    networks:
      - mynetwork

  web:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ../:/vol/development
    depends_on:
      - mysql
      - redis

  mysql:
    image: docker.io/mysql:8.0
    ports:
      - 3306:3306
    networks:
      - mynetwork
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - mynetwork
    volumes:
      - ../src/main/docker/redis.conf:/etc/redis.conf:rw
#      - ./data:/data:rw
    command:
      /bin/bash -c "redis-server /etc/redis.conf "

networks:
  mynetwork:
    external: true
